[2022-11-17T22:47:10.955+0000] {processor.py:154} INFO - Started process (PID=45) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T22:47:10.957+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T22:47:10.960+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:47:10.960+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T22:47:10.977+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:47:10.970+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T22:47:10.979+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T22:47:11.079+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.133 seconds
[2022-11-17T22:47:41.770+0000] {processor.py:154} INFO - Started process (PID=99) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T22:47:41.773+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T22:47:41.774+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:47:41.774+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T22:47:41.782+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:47:41.780+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T22:47:41.783+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T22:47:41.822+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.057 seconds
[2022-11-17T22:48:12.056+0000] {processor.py:154} INFO - Started process (PID=136) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T22:48:12.059+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T22:48:12.061+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:48:12.061+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T22:48:12.069+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:48:12.067+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T22:48:12.070+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T22:48:12.096+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.047 seconds
[2022-11-17T22:48:42.467+0000] {processor.py:154} INFO - Started process (PID=170) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T22:48:42.470+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T22:48:42.472+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:48:42.472+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T22:48:42.481+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:48:42.479+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T22:48:42.482+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T22:48:42.523+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.061 seconds
[2022-11-17T22:49:12.814+0000] {processor.py:154} INFO - Started process (PID=195) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T22:49:12.817+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T22:49:12.819+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:49:12.818+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T22:49:12.828+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:49:12.826+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T22:49:12.829+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T22:49:12.868+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.061 seconds
[2022-11-17T22:49:43.678+0000] {processor.py:154} INFO - Started process (PID=229) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T22:49:43.682+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T22:49:43.685+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:49:43.685+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T22:49:43.702+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:49:43.697+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T22:49:43.707+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T22:49:43.769+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.100 seconds
[2022-11-17T22:50:14.430+0000] {processor.py:154} INFO - Started process (PID=254) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T22:50:14.434+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T22:50:14.437+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:50:14.436+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T22:50:14.451+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:50:14.448+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T22:50:14.454+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T22:50:14.510+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.091 seconds
[2022-11-17T22:50:44.700+0000] {processor.py:154} INFO - Started process (PID=279) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T22:50:44.708+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T22:50:44.714+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:50:44.714+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T22:50:44.732+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:50:44.728+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T22:50:44.734+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T22:50:44.770+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.109 seconds
[2022-11-17T22:51:14.922+0000] {processor.py:154} INFO - Started process (PID=313) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T22:51:14.926+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T22:51:14.929+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:51:14.928+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T22:51:14.943+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:51:14.941+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T22:51:14.945+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T22:51:15.004+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.092 seconds
[2022-11-17T22:51:45.064+0000] {processor.py:154} INFO - Started process (PID=338) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T22:51:45.067+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T22:51:45.070+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:51:45.069+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T22:51:45.084+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:51:45.082+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T22:51:45.088+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T22:51:45.146+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.092 seconds
[2022-11-17T22:52:15.262+0000] {processor.py:154} INFO - Started process (PID=363) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T22:52:15.266+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T22:52:15.269+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:52:15.269+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T22:52:15.283+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:52:15.280+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T22:52:15.285+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T22:52:15.339+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.087 seconds
[2022-11-17T22:52:45.692+0000] {processor.py:154} INFO - Started process (PID=388) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T22:52:45.696+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T22:52:45.697+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:52:45.697+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T22:52:45.705+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:52:45.704+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T22:52:45.707+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T22:52:45.743+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.057 seconds
[2022-11-17T22:53:16.452+0000] {processor.py:154} INFO - Started process (PID=422) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T22:53:16.455+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T22:53:16.458+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:53:16.457+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T22:53:16.473+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:53:16.469+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T22:53:16.477+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T22:53:16.541+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.097 seconds
[2022-11-17T22:53:48.999+0000] {processor.py:154} INFO - Started process (PID=444) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T22:53:49.549+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T22:53:49.700+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:53:49.698+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T22:53:50.468+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:53:50.017+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T22:53:50.670+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T22:53:55.015+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 6.756 seconds
[2022-11-17T22:54:27.244+0000] {processor.py:154} INFO - Started process (PID=469) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T22:54:27.444+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T22:54:27.512+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:54:27.511+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T22:54:28.276+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:54:28.082+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T22:54:28.751+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T22:54:35.134+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 8.112 seconds
[2022-11-17T22:55:16.914+0000] {processor.py:154} INFO - Started process (PID=497) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T22:55:16.926+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T22:55:16.976+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:55:16.958+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T22:55:17.130+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:55:17.100+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T22:55:17.135+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T22:55:18.702+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 1.912 seconds
[2022-11-17T22:56:00.763+0000] {processor.py:154} INFO - Started process (PID=518) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T22:56:00.899+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T22:56:00.947+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:56:00.946+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T22:56:01.456+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:56:01.405+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T22:56:01.479+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T22:56:02.504+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 2.515 seconds
[2022-11-17T22:56:33.397+0000] {processor.py:154} INFO - Started process (PID=543) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T22:56:33.414+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T22:56:33.423+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:56:33.421+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T22:56:33.525+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:56:33.511+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T22:56:33.529+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T22:56:34.068+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.687 seconds
[2022-11-17T22:57:05.051+0000] {processor.py:154} INFO - Started process (PID=569) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T22:57:05.056+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T22:57:05.074+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:57:05.073+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T22:57:05.126+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:57:05.110+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T22:57:05.129+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T22:57:05.276+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.249 seconds
[2022-11-17T22:57:35.685+0000] {processor.py:154} INFO - Started process (PID=585) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T22:57:35.691+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T22:57:35.695+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:57:35.695+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T22:57:35.744+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:57:35.741+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T22:57:35.751+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T22:57:35.862+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.200 seconds
[2022-11-17T22:58:06.705+0000] {processor.py:154} INFO - Started process (PID=619) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T22:58:06.710+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T22:58:06.713+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:58:06.713+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T22:58:06.729+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:58:06.726+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T22:58:06.731+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T22:58:06.791+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.097 seconds
[2022-11-17T22:58:36.854+0000] {processor.py:154} INFO - Started process (PID=644) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T22:58:36.858+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T22:58:36.862+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:58:36.861+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T22:58:36.877+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:58:36.875+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T22:58:36.879+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T22:58:36.929+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.085 seconds
[2022-11-17T22:59:07.177+0000] {processor.py:154} INFO - Started process (PID=669) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T22:59:07.182+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T22:59:07.185+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:59:07.184+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T22:59:07.200+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:59:07.197+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T22:59:07.202+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T22:59:07.256+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.088 seconds
[2022-11-17T22:59:37.485+0000] {processor.py:154} INFO - Started process (PID=692) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T22:59:37.494+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T22:59:37.507+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:59:37.505+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T22:59:37.543+0000] {logging_mixin.py:120} INFO - [2022-11-17T22:59:37.530+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T22:59:37.556+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T22:59:37.633+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.174 seconds
[2022-11-17T23:00:07.847+0000] {processor.py:154} INFO - Started process (PID=723) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:00:07.854+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:00:07.866+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:00:07.858+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:00:07.900+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:00:07.885+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:00:07.904+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:00:08.019+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.203 seconds
[2022-11-17T23:00:38.173+0000] {processor.py:154} INFO - Started process (PID=741) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:00:38.179+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:00:38.194+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:00:38.193+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:00:38.222+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:00:38.219+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:00:38.224+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:00:38.319+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.170 seconds
[2022-11-17T23:01:08.421+0000] {processor.py:154} INFO - Started process (PID=766) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:01:08.426+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:01:08.429+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:01:08.429+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:01:08.458+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:01:08.456+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:01:08.470+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:01:08.548+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.139 seconds
[2022-11-17T23:01:38.880+0000] {processor.py:154} INFO - Started process (PID=791) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:01:38.887+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:01:38.891+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:01:38.891+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:01:38.906+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:01:38.903+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:01:38.910+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:01:38.983+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.118 seconds
[2022-11-17T23:02:09.217+0000] {processor.py:154} INFO - Started process (PID=816) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:02:09.230+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:02:09.234+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:02:09.233+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:02:09.271+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:02:09.266+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:02:09.273+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:02:09.365+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.161 seconds
[2022-11-17T23:02:40.200+0000] {processor.py:154} INFO - Started process (PID=841) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:02:40.218+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:02:40.234+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:02:40.233+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:02:40.310+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:02:40.305+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:02:40.327+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:02:40.598+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.437 seconds
[2022-11-17T23:03:11.783+0000] {processor.py:154} INFO - Started process (PID=864) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:03:11.850+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:03:11.970+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:03:11.968+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:03:12.553+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:03:12.402+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:03:12.603+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:03:13.473+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 1.959 seconds
[2022-11-17T23:03:50.299+0000] {processor.py:154} INFO - Started process (PID=885) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:03:50.445+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:03:50.516+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:03:50.515+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:03:50.791+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:03:50.739+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:03:50.810+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:03:52.632+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 2.786 seconds
[2022-11-17T23:04:24.594+0000] {processor.py:154} INFO - Started process (PID=903) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:04:24.647+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:04:24.762+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:04:24.733+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:04:25.230+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:04:24.999+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:04:25.247+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:04:27.372+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 2.957 seconds
[2022-11-17T23:04:58.393+0000] {processor.py:154} INFO - Started process (PID=926) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:04:58.412+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:04:58.466+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:04:58.466+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:04:58.685+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:04:58.574+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:04:58.723+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:04:59.066+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.845 seconds
[2022-11-17T23:05:47.644+0000] {processor.py:154} INFO - Started process (PID=953) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:05:47.680+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:05:47.716+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:05:47.703+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:05:47.830+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:05:47.809+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:05:47.848+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:05:48.585+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 1.122 seconds
[2022-11-17T23:06:19.324+0000] {processor.py:154} INFO - Started process (PID=975) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:06:19.344+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:06:19.361+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:06:19.350+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:06:19.422+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:06:19.417+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:06:19.438+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:06:19.750+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.497 seconds
[2022-11-17T23:06:50.448+0000] {processor.py:154} INFO - Started process (PID=992) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:06:50.470+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:06:50.493+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:06:50.492+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:06:50.604+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:06:50.581+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:06:50.612+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:06:51.449+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 1.133 seconds
[2022-11-17T23:07:21.921+0000] {processor.py:154} INFO - Started process (PID=1015) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:07:21.938+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:07:21.955+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:07:21.954+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:07:22.023+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:07:22.007+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:07:22.038+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:07:22.636+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.749 seconds
[2022-11-17T23:07:53.765+0000] {processor.py:154} INFO - Started process (PID=1037) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:07:53.783+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:07:53.806+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:07:53.806+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:07:53.872+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:07:53.852+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:07:53.879+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:07:54.142+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.470 seconds
[2022-11-17T23:08:24.604+0000] {processor.py:154} INFO - Started process (PID=1054) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:08:24.637+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:08:24.687+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:08:24.657+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:08:24.803+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:08:24.786+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:08:24.822+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:08:25.557+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 1.018 seconds
[2022-11-17T23:08:55.862+0000] {processor.py:154} INFO - Started process (PID=1078) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:08:55.868+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:08:55.872+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:08:55.871+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:08:55.924+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:08:55.904+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:08:55.927+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:08:56.056+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.225 seconds
[2022-11-17T23:09:26.837+0000] {processor.py:154} INFO - Started process (PID=1103) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:09:26.840+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:09:26.842+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:09:26.842+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:09:26.855+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:09:26.853+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:09:26.857+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:09:26.897+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.069 seconds
[2022-11-17T23:15:18.308+0000] {processor.py:154} INFO - Started process (PID=55) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:15:18.320+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:15:18.328+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:15:18.328+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:15:18.354+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:15:18.348+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:15:18.357+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:15:18.452+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.178 seconds
[2022-11-17T23:15:48.797+0000] {processor.py:154} INFO - Started process (PID=79) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:15:48.814+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:15:48.864+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:15:48.821+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:15:48.948+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:15:48.927+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:15:49.011+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:15:49.237+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.485 seconds
[2022-11-17T23:16:21.277+0000] {processor.py:154} INFO - Started process (PID=93) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:16:21.807+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:16:21.956+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:16:21.900+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:16:22.649+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:16:22.425+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:16:22.775+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:16:24.561+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 3.972 seconds
[2022-11-17T23:16:55.538+0000] {processor.py:154} INFO - Started process (PID=121) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:16:55.554+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:16:55.558+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:16:55.558+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:16:55.600+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:16:55.597+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:16:55.602+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:16:55.734+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.219 seconds
[2022-11-17T23:17:25.901+0000] {processor.py:154} INFO - Started process (PID=146) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:17:25.904+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:17:25.907+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:17:25.907+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:17:25.920+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:17:25.918+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:17:25.922+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:17:25.976+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.087 seconds
[2022-11-17T23:17:56.501+0000] {processor.py:154} INFO - Started process (PID=171) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:17:56.504+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:17:56.507+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:17:56.507+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:17:56.523+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:17:56.520+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:17:56.526+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:17:56.583+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.088 seconds
[2022-11-17T23:18:27.012+0000] {processor.py:154} INFO - Started process (PID=213) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:18:27.014+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:18:27.015+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:18:27.015+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:18:27.022+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:18:27.021+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:18:27.024+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:18:27.055+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.048 seconds
[2022-11-17T23:18:57.232+0000] {processor.py:154} INFO - Started process (PID=250) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:18:57.234+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:18:57.235+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:18:57.235+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:18:57.242+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:18:57.241+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:18:57.244+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:18:57.274+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.047 seconds
[2022-11-17T23:19:27.973+0000] {processor.py:154} INFO - Started process (PID=275) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:19:27.976+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:19:27.978+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:19:27.978+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:19:27.988+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:19:27.986+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:19:27.990+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:19:28.033+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.072 seconds
[2022-11-17T23:19:58.485+0000] {processor.py:154} INFO - Started process (PID=309) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:19:58.489+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:19:58.492+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:19:58.491+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:19:58.505+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:19:58.503+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:19:58.507+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:19:58.564+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.089 seconds
[2022-11-17T23:20:29.182+0000] {processor.py:154} INFO - Started process (PID=332) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:20:29.198+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:20:29.202+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:20:29.202+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:20:29.232+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:20:29.227+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:20:29.249+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:20:29.408+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.238 seconds
[2022-11-17T23:20:59.798+0000] {processor.py:154} INFO - Started process (PID=355) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:20:59.813+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:20:59.818+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:20:59.818+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:20:59.851+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:20:59.847+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:20:59.864+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:20:59.992+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.217 seconds
[2022-11-17T23:21:30.176+0000] {processor.py:154} INFO - Started process (PID=373) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:21:30.180+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:21:30.183+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:21:30.183+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:21:30.201+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:21:30.198+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:21:30.204+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:21:30.268+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.101 seconds
[2022-11-17T23:22:00.859+0000] {processor.py:154} INFO - Started process (PID=407) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:22:00.862+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:22:00.864+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:22:00.864+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:22:00.872+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:22:00.870+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:22:00.873+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:22:00.909+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.056 seconds
[2022-11-17T23:22:31.362+0000] {processor.py:154} INFO - Started process (PID=441) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:22:31.366+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:22:31.368+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:22:31.368+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:22:31.378+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:22:31.376+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:22:31.379+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:22:31.412+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.056 seconds
[2022-11-17T23:23:01.677+0000] {processor.py:154} INFO - Started process (PID=466) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:23:01.680+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:23:01.682+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:23:01.682+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:23:01.692+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:23:01.690+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:23:01.693+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:23:01.738+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.069 seconds
[2022-11-17T23:23:32.260+0000] {processor.py:154} INFO - Started process (PID=497) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:23:32.264+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:23:32.268+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:23:32.268+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:23:32.284+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:23:32.281+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:23:32.287+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:23:32.348+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.099 seconds
[2022-11-17T23:24:03.632+0000] {processor.py:154} INFO - Started process (PID=515) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:24:03.672+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:24:03.718+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:24:03.705+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:24:04.219+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:24:04.105+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:24:04.253+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:24:05.307+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 1.936 seconds
[2022-11-17T23:24:36.677+0000] {processor.py:154} INFO - Started process (PID=541) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:24:36.817+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:24:37.103+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:24:37.073+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:24:37.426+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:24:37.328+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:24:37.452+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:24:37.764+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 1.250 seconds
[2022-11-17T23:25:08.422+0000] {processor.py:154} INFO - Started process (PID=564) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:25:08.427+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:25:08.447+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:25:08.445+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:25:08.496+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:25:08.481+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:25:08.499+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:25:08.774+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.379 seconds
[2022-11-17T23:25:41.669+0000] {processor.py:154} INFO - Started process (PID=586) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:25:42.473+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:25:42.590+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:25:42.588+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:25:42.804+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:25:42.755+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:25:42.839+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:25:44.298+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 3.040 seconds
[2022-11-17T23:26:14.609+0000] {processor.py:154} INFO - Started process (PID=604) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:26:14.613+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:26:14.617+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:26:14.616+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:26:14.632+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:26:14.629+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:26:14.635+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:26:14.700+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.103 seconds
[2022-11-17T23:26:45.224+0000] {processor.py:154} INFO - Started process (PID=637) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:26:45.229+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:26:45.232+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:26:45.231+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:26:45.247+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:26:45.243+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:26:45.249+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:26:45.298+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.086 seconds
[2022-11-17T23:28:55.637+0000] {processor.py:154} INFO - Started process (PID=61) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:28:55.669+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:28:55.720+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:28:55.678+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:28:55.780+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:28:55.760+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:28:55.787+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:28:56.019+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.470 seconds
[2022-11-17T23:29:29.257+0000] {processor.py:154} INFO - Started process (PID=76) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:29:29.478+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:29:29.692+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:29:29.691+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:29:31.381+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:29:31.313+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:29:31.498+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:29:42.048+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 13.392 seconds
[2022-11-17T23:30:13.275+0000] {processor.py:154} INFO - Started process (PID=108) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:30:13.305+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:30:13.330+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:30:13.330+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:30:13.418+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:30:13.409+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:30:13.425+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:30:13.681+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.506 seconds
[2022-11-17T23:30:44.514+0000] {processor.py:154} INFO - Started process (PID=123) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:30:44.519+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:30:44.533+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:30:44.522+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:30:44.581+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:30:44.564+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:30:44.589+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:30:44.744+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.254 seconds
[2022-11-17T23:31:15.715+0000] {processor.py:154} INFO - Started process (PID=148) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:31:15.723+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:31:15.745+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:31:15.744+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:31:15.894+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:31:15.851+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:31:15.901+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:31:16.500+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.962 seconds
[2022-11-17T23:31:47.234+0000] {processor.py:154} INFO - Started process (PID=164) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:31:47.244+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:31:47.263+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:31:47.261+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:31:47.324+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:31:47.307+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:31:47.330+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:31:47.472+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.267 seconds
[2022-11-17T23:32:18.676+0000] {processor.py:154} INFO - Started process (PID=190) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:32:18.702+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:32:18.732+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:32:18.707+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:32:18.778+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:32:18.773+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:32:18.782+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:32:19.121+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.474 seconds
[2022-11-17T23:33:07.248+0000] {processor.py:154} INFO - Started process (PID=214) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:33:07.274+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:33:07.290+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:33:07.290+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:33:07.458+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:33:07.436+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:33:07.492+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:33:08.124+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 1.252 seconds
[2022-11-17T23:33:38.855+0000] {processor.py:154} INFO - Started process (PID=240) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:33:38.872+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:33:38.884+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:33:38.881+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:33:38.984+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:33:38.981+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:33:38.994+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:33:39.371+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.550 seconds
[2022-11-17T23:34:34.961+0000] {processor.py:154} INFO - Started process (PID=274) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:34:34.973+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:34:34.977+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:34:34.977+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:34:35.033+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:34:35.017+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:34:35.040+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:34:35.286+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.385 seconds
[2022-11-17T23:35:05.514+0000] {processor.py:154} INFO - Started process (PID=301) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:35:05.518+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:35:05.522+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:35:05.522+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:35:05.536+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:35:05.533+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:35:05.538+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:35:05.588+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.084 seconds
[2022-11-17T23:35:36.225+0000] {processor.py:154} INFO - Started process (PID=323) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:35:36.228+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:35:36.231+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:35:36.230+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:35:36.243+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:35:36.241+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 20
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:35:36.245+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:35:36.301+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.086 seconds
[2022-11-17T23:35:46.786+0000] {processor.py:154} INFO - Started process (PID=337) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:35:46.789+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:35:46.792+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:35:46.791+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:35:46.811+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:35:46.809+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 19
    transfrom = transform_tasks()
                                ^
IndentationError: unindent does not match any outer indentation level
[2022-11-17T23:35:46.813+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:35:46.858+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.080 seconds
[2022-11-17T23:36:00.004+0000] {processor.py:154} INFO - Started process (PID=347) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:36:00.008+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:36:00.010+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:36:00.010+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:36:00.059+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:36:00.055+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 3, in <module>
    from groups.group_downloads import download_tasks
ImportError: cannot import name 'download_tasks' from 'groups.group_downloads' (/opt/airflow/dags/groups/group_downloads.py)
[2022-11-17T23:36:00.061+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:36:00.107+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.113 seconds
[2022-11-17T23:36:30.280+0000] {processor.py:154} INFO - Started process (PID=381) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:36:30.286+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:36:30.289+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:36:30.289+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:36:30.335+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:36:30.328+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 3, in <module>
    from groups.group_downloads import download_tasks
ImportError: cannot import name 'download_tasks' from 'groups.group_downloads' (/opt/airflow/dags/groups/group_downloads.py)
[2022-11-17T23:36:30.338+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:36:30.407+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.141 seconds
[2022-11-17T23:37:00.890+0000] {processor.py:154} INFO - Started process (PID=407) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:37:00.908+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:37:00.912+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:37:00.912+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:37:01.026+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:37:01.021+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 12, in <module>
    downloads = download_tasks()
TypeError: download_tasks() missing 3 required positional arguments: 'parent_dag_id', 'child_dag_id', and 'args'
[2022-11-17T23:37:01.029+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:37:01.137+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.259 seconds
[2022-11-17T23:37:39.201+0000] {processor.py:154} INFO - Started process (PID=429) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:37:39.281+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:37:39.382+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:37:39.380+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:37:41.022+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:37:40.985+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 12, in <module>
    downloads = download_tasks()
TypeError: download_tasks() missing 3 required positional arguments: 'parent_dag_id', 'child_dag_id', and 'args'
[2022-11-17T23:37:41.039+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:37:42.209+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 3.264 seconds
[2022-11-17T23:38:12.505+0000] {processor.py:154} INFO - Started process (PID=446) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:38:12.511+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:38:12.513+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:38:12.513+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:38:12.559+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:38:12.555+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 12, in <module>
    downloads = download_tasks()
TypeError: download_tasks() missing 3 required positional arguments: 'parent_dag_id', 'child_dag_id', and 'args'
[2022-11-17T23:38:12.561+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:38:12.610+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.115 seconds
[2022-11-17T23:38:43.099+0000] {processor.py:154} INFO - Started process (PID=479) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:38:43.103+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:38:43.104+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:38:43.104+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:38:43.133+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:38:43.130+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 12, in <module>
    downloads = download_tasks()
TypeError: download_tasks() missing 3 required positional arguments: 'parent_dag_id', 'child_dag_id', and 'args'
[2022-11-17T23:38:43.134+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:38:43.165+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.072 seconds
[2022-11-17T23:39:13.561+0000] {processor.py:154} INFO - Started process (PID=504) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:39:13.564+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:39:13.565+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:39:13.565+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:39:13.587+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:39:13.586+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 12, in <module>
    downloads = download_tasks()
TypeError: download_tasks() missing 3 required positional arguments: 'parent_dag_id', 'child_dag_id', and 'args'
[2022-11-17T23:39:13.588+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:39:13.614+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.057 seconds
[2022-11-17T23:39:44.071+0000] {processor.py:154} INFO - Started process (PID=539) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:39:44.073+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:39:44.075+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:39:44.075+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:39:44.107+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:39:44.105+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag.py", line 12, in <module>
    downloads = download_tasks()
TypeError: download_tasks() missing 3 required positional arguments: 'parent_dag_id', 'child_dag_id', and 'args'
[2022-11-17T23:39:44.109+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:39:44.138+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.075 seconds
[2022-11-17T23:40:14.651+0000] {processor.py:154} INFO - Started process (PID=573) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:40:14.655+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:40:14.659+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:40:14.659+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:40:14.722+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:40:14.969+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:40:14.969+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:40:15.032+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:40:15.032+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:40:15.099+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.456 seconds
[2022-11-17T23:40:45.143+0000] {processor.py:154} INFO - Started process (PID=598) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:40:45.159+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:40:45.164+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:40:45.163+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:40:45.457+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:40:45.839+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:40:45.838+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:40:46.701+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:40:46.700+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:40:47.504+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 2.394 seconds
[2022-11-17T23:41:23.500+0000] {processor.py:154} INFO - Started process (PID=618) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:41:23.530+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:41:23.551+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:41:23.550+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:41:23.829+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:41:24.955+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:41:24.953+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:41:25.986+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:41:25.985+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:41:27.085+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 3.822 seconds
[2022-11-17T23:41:57.856+0000] {processor.py:154} INFO - Started process (PID=637) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:41:57.871+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:41:57.874+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:41:57.874+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:41:57.989+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:41:58.201+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:41:58.200+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:41:58.615+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:41:58.614+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:41:58.732+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.889 seconds
[2022-11-17T23:42:40.440+0000] {processor.py:154} INFO - Started process (PID=659) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:42:40.502+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:42:40.525+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:42:40.524+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:42:40.983+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:42:41.640+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:42:41.639+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:42:42.028+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:42:42.028+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:42:42.294+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 1.949 seconds
[2022-11-17T23:43:13.057+0000] {processor.py:154} INFO - Started process (PID=694) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:43:13.060+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:43:13.062+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:43:13.062+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:43:13.113+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:43:13.187+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:43:13.187+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:43:13.237+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:43:13.237+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:43:13.271+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.224 seconds
[2022-11-17T23:43:43.330+0000] {processor.py:154} INFO - Started process (PID=720) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:43:43.332+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:43:43.333+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:43:43.333+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:43:43.360+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:43:43.409+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:43:43.409+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:43:43.444+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:43:43.444+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:43:43.466+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.141 seconds
[2022-11-17T23:44:13.691+0000] {processor.py:154} INFO - Started process (PID=752) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:44:13.693+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:44:13.694+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:44:13.694+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:44:13.731+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:44:13.787+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:44:13.787+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:44:13.826+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:44:13.826+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:44:13.852+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.167 seconds
[2022-11-17T23:44:44.360+0000] {processor.py:154} INFO - Started process (PID=777) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:44:44.364+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:44:44.367+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:44:44.367+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:44:44.427+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:44:44.534+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:44:44.533+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:44:44.593+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:44:44.593+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:44:44.631+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.279 seconds
[2022-11-17T23:45:15.083+0000] {processor.py:154} INFO - Started process (PID=809) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:45:15.086+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:45:15.087+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:45:15.087+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:45:15.127+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:45:15.192+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:45:15.192+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:45:15.233+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:45:15.232+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:45:15.262+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.184 seconds
[2022-11-17T23:45:45.338+0000] {processor.py:154} INFO - Started process (PID=844) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:45:45.342+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:45:45.343+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:45:45.343+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:45:45.370+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:45:45.418+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:45:45.418+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:45:45.458+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:45:45.458+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:45:45.484+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.150 seconds
[2022-11-17T23:46:15.829+0000] {processor.py:154} INFO - Started process (PID=868) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:46:15.832+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:46:15.834+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:46:15.833+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:46:15.872+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:46:15.940+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:46:15.940+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:46:15.985+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:46:15.984+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:46:16.013+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.190 seconds
[2022-11-17T23:46:46.112+0000] {processor.py:154} INFO - Started process (PID=902) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:46:46.117+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:46:46.121+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:46:46.120+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:46:46.240+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:46:46.380+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:46:46.380+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:46:46.482+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:46:46.482+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:46:46.556+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.462 seconds
[2022-11-17T23:47:17.344+0000] {processor.py:154} INFO - Started process (PID=928) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:47:17.348+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:47:17.351+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:47:17.351+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:47:17.464+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:47:17.654+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:47:17.653+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:47:17.789+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:47:17.788+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:47:17.865+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.543 seconds
[2022-11-17T23:47:52.988+0000] {processor.py:154} INFO - Started process (PID=951) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:47:53.136+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:47:53.304+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:47:53.287+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:47:55.950+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:47:58.391+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:47:58.391+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:47:59.035+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:47:59.035+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:47:59.237+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 6.848 seconds
[2022-11-17T23:48:31.167+0000] {processor.py:154} INFO - Started process (PID=976) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:48:31.275+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:48:31.281+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:48:31.281+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:48:32.168+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:48:34.140+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:48:34.124+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:48:36.800+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:48:36.778+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:48:39.826+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 8.860 seconds
[2022-11-17T23:49:10.745+0000] {processor.py:154} INFO - Started process (PID=1003) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:49:10.761+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:49:10.764+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:49:10.764+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:49:10.933+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:49:11.162+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:49:11.161+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:49:11.332+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:49:11.331+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:49:11.429+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.712 seconds
[2022-11-17T23:49:42.453+0000] {processor.py:154} INFO - Started process (PID=1030) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:49:42.460+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:49:42.463+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:49:42.463+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:49:42.543+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:49:42.688+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:49:42.688+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:49:42.790+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:49:42.789+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:49:42.859+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.423 seconds
[2022-11-17T23:50:13.448+0000] {processor.py:154} INFO - Started process (PID=1056) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:50:13.475+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:50:13.480+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:50:13.479+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:50:13.761+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:50:14.032+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:50:14.031+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:50:14.158+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:50:14.157+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:50:14.246+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.843 seconds
[2022-11-17T23:50:44.613+0000] {processor.py:154} INFO - Started process (PID=1082) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:50:44.619+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:50:44.626+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:50:44.625+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:50:44.756+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:50:44.983+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:50:44.982+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:50:45.129+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:50:45.128+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:50:45.217+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.636 seconds
[2022-11-17T23:51:15.531+0000] {processor.py:154} INFO - Started process (PID=1107) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:51:15.541+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:51:15.551+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:51:15.550+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:51:15.659+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:51:15.832+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:51:15.832+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:51:15.952+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:51:15.952+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:51:16.018+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.500 seconds
[2022-11-17T23:51:46.429+0000] {processor.py:154} INFO - Started process (PID=1133) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:51:46.434+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:51:46.449+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:51:46.437+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:51:46.602+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:51:46.851+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:51:46.850+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:51:47.011+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:51:47.011+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:51:47.113+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.710 seconds
[2022-11-17T23:52:17.580+0000] {processor.py:154} INFO - Started process (PID=1159) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:52:17.598+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:52:17.619+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:52:17.607+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:52:17.805+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:52:18.157+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:52:18.157+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:52:18.380+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:52:18.380+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:52:18.547+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 1.017 seconds
[2022-11-17T23:52:48.917+0000] {processor.py:154} INFO - Started process (PID=1176) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:52:48.936+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:52:48.940+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:52:48.940+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:52:49.195+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:52:50.032+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:52:50.031+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:52:51.139+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:52:51.139+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:52:52.233+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 3.402 seconds
[2022-11-17T23:53:23.601+0000] {processor.py:154} INFO - Started process (PID=1200) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:53:23.617+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:53:23.622+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:53:23.621+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:53:23.929+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:53:24.606+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:53:24.605+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:53:25.167+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:53:25.153+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:53:25.808+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 2.229 seconds
[2022-11-17T23:53:56.630+0000] {processor.py:154} INFO - Started process (PID=1226) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:53:56.636+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:53:56.651+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:53:56.650+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:53:57.054+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:53:57.637+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:53:57.637+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:53:58.001+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:53:58.001+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:53:58.199+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 1.653 seconds
[2022-11-17T23:54:46.318+0000] {processor.py:154} INFO - Started process (PID=1245) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:54:46.331+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:54:46.350+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:54:46.349+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:54:46.561+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:54:47.043+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:54:47.040+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:54:48.267+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:54:48.265+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:54:49.157+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 2.866 seconds
[2022-11-17T23:55:20.311+0000] {processor.py:154} INFO - Started process (PID=1275) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:55:20.318+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:55:20.323+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:55:20.322+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:55:20.430+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:55:20.574+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:55:20.573+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:55:20.681+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:55:20.681+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:55:20.741+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.445 seconds
[2022-11-17T23:55:51.304+0000] {processor.py:154} INFO - Started process (PID=1301) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:55:51.309+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:55:51.313+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:55:51.312+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:55:51.471+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:55:51.758+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:55:51.758+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:55:51.995+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:55:51.994+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:55:52.126+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.847 seconds
[2022-11-17T23:56:22.402+0000] {processor.py:154} INFO - Started process (PID=1326) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:56:22.407+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:56:22.423+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:56:22.422+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:56:22.606+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:56:22.882+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:56:22.881+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:56:23.105+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:56:23.104+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:56:23.251+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.899 seconds
[2022-11-17T23:56:53.352+0000] {processor.py:154} INFO - Started process (PID=1352) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:56:53.357+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:56:53.362+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:56:53.361+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:56:53.456+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:56:53.611+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:56:53.610+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:56:53.713+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:56:53.710+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:56:53.780+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.441 seconds
[2022-11-17T23:57:24.049+0000] {processor.py:154} INFO - Started process (PID=1378) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:57:24.054+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:57:24.058+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:57:24.058+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:57:24.180+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:57:24.373+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:57:24.373+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:57:24.495+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:57:24.494+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:57:24.565+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.535 seconds
[2022-11-17T23:57:54.898+0000] {processor.py:154} INFO - Started process (PID=1405) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:57:54.902+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:57:54.905+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:57:54.905+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:57:54.970+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:57:55.079+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:57:55.078+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:57:55.152+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:57:55.152+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:57:55.200+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.311 seconds
[2022-11-17T23:58:25.698+0000] {processor.py:154} INFO - Started process (PID=1432) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:58:25.702+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:58:25.706+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:58:25.706+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:58:25.805+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:58:25.955+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:58:25.955+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:58:26.088+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:58:26.088+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:58:26.167+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.482 seconds
[2022-11-17T23:58:56.748+0000] {processor.py:154} INFO - Started process (PID=1458) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:58:56.753+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:58:56.756+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:58:56.756+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:58:56.866+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:58:57.003+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:58:57.003+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:58:57.092+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:58:57.092+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:58:57.167+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.430 seconds
[2022-11-17T23:59:27.473+0000] {processor.py:154} INFO - Started process (PID=1485) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:59:27.477+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:59:27.480+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:59:27.480+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:59:27.568+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:59:27.701+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:59:27.700+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:59:27.795+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:59:27.795+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:59:27.917+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.455 seconds
[2022-11-17T23:59:58.101+0000] {processor.py:154} INFO - Started process (PID=1513) to work on /opt/airflow/dags/group_dag.py
[2022-11-17T23:59:58.119+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag.py for tasks to queue
[2022-11-17T23:59:58.122+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:59:58.122+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag.py
[2022-11-17T23:59:58.295+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag']) retrieved from /opt/airflow/dags/group_dag.py
[2022-11-17T23:59:58.634+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:59:58.633+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-17T23:59:58.829+0000] {logging_mixin.py:120} INFO - [2022-11-17T23:59:58.829+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2022-11-16T00:00:00+00:00, run_after=2022-11-17T00:00:00+00:00
[2022-11-17T23:59:58.943+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag.py took 0.870 seconds
