[2022-11-10T00:00:01.903+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2022-11-09T00:00:00+00:00 [queued]>
[2022-11-10T00:00:01.913+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2022-11-09T00:00:00+00:00 [queued]>
[2022-11-10T00:00:01.914+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-10T00:00:01.915+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-10T00:00:01.915+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-10T00:00:01.928+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2022-11-09 00:00:00+00:00
[2022-11-10T00:00:01.934+0000] {standard_task_runner.py:55} INFO - Started process 400 to run task
[2022-11-10T00:00:01.939+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2022-11-09T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmppqe5qsta']
[2022-11-10T00:00:01.942+0000] {standard_task_runner.py:83} INFO - Job 26: Subtask create_table
[2022-11-10T00:00:01.995+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table scheduled__2022-11-09T00:00:00+00:00 [running]> on host 6abb7f022470
[2022-11-10T00:00:02.063+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-09T00:00:00+00:00
[2022-11-10T00:00:02.074+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2022-11-10T00:00:02.078+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2022-11-10T00:00:02.080+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2022-11-10T00:00:02.090+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20221109T000000, start_date=20221110T000001, end_date=20221110T000002
[2022-11-10T00:00:02.132+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-11-10T00:00:02.163+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
