[2022-11-09T23:15:07.110+0000] {processor.py:154} INFO - Started process (PID=781) to work on /opt/airflow/dags/comsumer.py
[2022-11-09T23:15:07.144+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/comsumer.py for tasks to queue
[2022-11-09T23:15:07.242+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:15:07.229+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/comsumer.py
[2022-11-09T23:15:07.778+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:15:07.644+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/comsumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/comsumer.py", line 14, in <module>
    @task
NameError: name 'task' is not defined
[2022-11-09T23:15:07.845+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/comsumer.py
[2022-11-09T23:15:08.818+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/comsumer.py took 1.956 seconds
[2022-11-09T23:15:39.589+0000] {processor.py:154} INFO - Started process (PID=830) to work on /opt/airflow/dags/comsumer.py
[2022-11-09T23:15:39.594+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/comsumer.py for tasks to queue
[2022-11-09T23:15:39.598+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:15:39.597+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/comsumer.py
[2022-11-09T23:15:39.628+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:15:39.623+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/comsumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/comsumer.py", line 14, in <module>
    @task
NameError: name 'task' is not defined
[2022-11-09T23:15:39.631+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/comsumer.py
[2022-11-09T23:15:39.718+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/comsumer.py took 0.148 seconds
[2022-11-09T23:16:09.935+0000] {processor.py:154} INFO - Started process (PID=887) to work on /opt/airflow/dags/comsumer.py
[2022-11-09T23:16:09.939+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/comsumer.py for tasks to queue
[2022-11-09T23:16:09.942+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:16:09.941+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/comsumer.py
[2022-11-09T23:16:09.961+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:16:09.956+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/comsumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/comsumer.py", line 14, in <module>
    @task
NameError: name 'task' is not defined
[2022-11-09T23:16:09.963+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/comsumer.py
[2022-11-09T23:16:10.023+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/comsumer.py took 0.097 seconds
[2022-11-09T23:16:40.496+0000] {processor.py:154} INFO - Started process (PID=953) to work on /opt/airflow/dags/comsumer.py
[2022-11-09T23:16:40.501+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/comsumer.py for tasks to queue
[2022-11-09T23:16:40.504+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:16:40.503+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/comsumer.py
[2022-11-09T23:16:40.528+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:16:40.523+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/comsumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/comsumer.py", line 14, in <module>
    @task
NameError: name 'task' is not defined
[2022-11-09T23:16:40.530+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/comsumer.py
[2022-11-09T23:16:40.609+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/comsumer.py took 0.129 seconds
[2022-11-09T23:17:24.166+0000] {processor.py:154} INFO - Started process (PID=1000) to work on /opt/airflow/dags/comsumer.py
[2022-11-09T23:17:24.214+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/comsumer.py for tasks to queue
[2022-11-09T23:17:24.249+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:17:24.232+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/comsumer.py
[2022-11-09T23:17:24.564+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:17:24.433+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/comsumer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/comsumer.py", line 14, in <module>
    @task
NameError: name 'task' is not defined
[2022-11-09T23:17:24.581+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/comsumer.py
[2022-11-09T23:17:25.349+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/comsumer.py took 1.333 seconds
[2022-11-09T23:18:46.603+0000] {processor.py:154} INFO - Started process (PID=1060) to work on /opt/airflow/dags/comsumer.py
[2022-11-09T23:18:46.619+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/comsumer.py for tasks to queue
[2022-11-09T23:18:46.628+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:18:46.627+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/comsumer.py
[2022-11-09T23:18:46.974+0000] {processor.py:766} INFO - DAG(s) dict_keys(['producer']) retrieved from /opt/airflow/dags/comsumer.py
[2022-11-09T23:18:47.700+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:18:47.700+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-09T23:18:47.976+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:18:47.976+0000] {dag.py:3340} INFO - Setting next_dagrun for producer to None, run_after=None
[2022-11-09T23:18:48.323+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/comsumer.py took 1.748 seconds
[2022-11-09T23:19:19.076+0000] {processor.py:154} INFO - Started process (PID=1119) to work on /opt/airflow/dags/comsumer.py
[2022-11-09T23:19:19.081+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/comsumer.py for tasks to queue
[2022-11-09T23:19:19.100+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:19:19.099+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/comsumer.py
[2022-11-09T23:19:19.259+0000] {processor.py:766} INFO - DAG(s) dict_keys(['producer']) retrieved from /opt/airflow/dags/comsumer.py
[2022-11-09T23:19:19.826+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:19:19.826+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-09T23:19:19.975+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:19:19.975+0000] {dag.py:3340} INFO - Setting next_dagrun for producer to None, run_after=None
[2022-11-09T23:19:20.111+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/comsumer.py took 1.061 seconds
[2022-11-09T23:20:16.429+0000] {processor.py:154} INFO - Started process (PID=1174) to work on /opt/airflow/dags/comsumer.py
[2022-11-09T23:20:16.451+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/comsumer.py for tasks to queue
[2022-11-09T23:20:16.478+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:20:16.476+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/comsumer.py
[2022-11-09T23:20:16.743+0000] {processor.py:766} INFO - DAG(s) dict_keys(['producer']) retrieved from /opt/airflow/dags/comsumer.py
[2022-11-09T23:20:17.120+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:20:17.119+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-09T23:20:17.404+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:20:17.404+0000] {dag.py:3340} INFO - Setting next_dagrun for producer to None, run_after=None
[2022-11-09T23:20:17.572+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/comsumer.py took 1.155 seconds
[2022-11-09T23:20:47.990+0000] {processor.py:154} INFO - Started process (PID=1233) to work on /opt/airflow/dags/comsumer.py
[2022-11-09T23:20:47.996+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/comsumer.py for tasks to queue
[2022-11-09T23:20:48.010+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:20:48.009+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/comsumer.py
[2022-11-09T23:20:48.140+0000] {processor.py:766} INFO - DAG(s) dict_keys(['producer']) retrieved from /opt/airflow/dags/comsumer.py
[2022-11-09T23:20:48.903+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:20:48.902+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-09T23:20:49.014+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:20:49.014+0000] {dag.py:3340} INFO - Setting next_dagrun for producer to None, run_after=None
[2022-11-09T23:20:49.134+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/comsumer.py took 1.169 seconds
[2022-11-09T23:21:26.805+0000] {processor.py:154} INFO - Started process (PID=1274) to work on /opt/airflow/dags/comsumer.py
[2022-11-09T23:21:26.838+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/comsumer.py for tasks to queue
[2022-11-09T23:21:26.922+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:21:26.909+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/comsumer.py
[2022-11-09T23:21:28.059+0000] {processor.py:766} INFO - DAG(s) dict_keys(['consumer']) retrieved from /opt/airflow/dags/comsumer.py
[2022-11-09T23:21:31.012+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:21:31.011+0000] {manager.py:507} INFO - Created Permission View: can delete on DAG:consumer
[2022-11-09T23:21:31.179+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:21:31.179+0000] {manager.py:507} INFO - Created Permission View: can edit on DAG:consumer
[2022-11-09T23:21:31.428+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:21:31.427+0000] {manager.py:507} INFO - Created Permission View: can read on DAG:consumer
[2022-11-09T23:21:31.443+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:21:31.442+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-09T23:21:32.211+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:21:32.197+0000] {dag.py:2606} INFO - Creating ORM DAG for consumer
[2022-11-09T23:21:32.612+0000] {logging_mixin.py:120} INFO - [2022-11-09T23:21:32.600+0000] {dag.py:3340} INFO - Setting next_dagrun for consumer to None, run_after=None
[2022-11-09T23:21:32.734+0000] {processor.py:179} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 175, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 159, in _handle_dag_file_processing
    callback_requests=callback_requests,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 781, in process_file
    dagbag.sync_to_db(processor_subdir=self._dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 644, in sync_to_db
    for attempt in run_with_db_retries(logger=self.log):
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 384, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 351, in iter
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 659, in sync_to_db
    self.dags.values(), processor_subdir=processor_subdir, session=session
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2687, in bulk_write_to_db
    DagCode.bulk_sync_to_db(filelocs, session=session)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagcode.py", line 117, in bulk_sync_to_db
    os.path.getmtime(correct_maybe_zipped(fileloc)), tz=timezone.utc
  File "/usr/local/lib/python3.7/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/comsumer.py'
