[2022-11-09 08:29:16,623] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2022-11-08T00:00:00+00:00 [queued]>
[2022-11-09 08:29:16,693] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2022-11-08T00:00:00+00:00 [queued]>
[2022-11-09 08:29:16,695] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-09 08:29:16,698] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-11-09 08:29:16,700] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-09 08:29:16,778] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-11-08 00:00:00+00:00
[2022-11-09 08:29:16,818] {standard_task_runner.py:52} INFO - Started process 7235 to run task
[2022-11-09 08:29:16,842] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2022-11-08T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpznf4yo4n', '--error-file', '/tmp/tmpthzst56l']
[2022-11-09 08:29:16,847] {standard_task_runner.py:80} INFO - Job 7: Subtask create_table
[2022-11-09 08:29:17,195] {task_command.py:369} INFO - Running <TaskInstance: user_processing.create_table scheduled__2022-11-08T00:00:00+00:00 [running]> on host ce8aab517b0f
[2022-11-09 08:29:17,600] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-08T00:00:00+00:00
[2022-11-09 08:29:17,668] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-11-09 08:29:17,696] {dbapi.py:208} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2022-11-09 08:29:17,701] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2022-11-09 08:29:17,796] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20221108T000000, start_date=20221109T082916, end_date=20221109T082917
[2022-11-09 08:29:17,942] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-09 08:29:18,204] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
