[2022-11-09 08:17:09,132] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2022-11-08T00:00:00+00:00 [queued]>
[2022-11-09 08:17:09,330] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2022-11-08T00:00:00+00:00 [queued]>
[2022-11-09 08:17:09,364] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-09 08:17:09,381] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-09 08:17:09,385] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-09 08:17:10,118] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-11-08 00:00:00+00:00
[2022-11-09 08:17:10,505] {standard_task_runner.py:52} INFO - Started process 6885 to run task
[2022-11-09 08:17:10,923] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2022-11-08T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpevmrvit6', '--error-file', '/tmp/tmp_8h088vt']
[2022-11-09 08:17:11,002] {standard_task_runner.py:80} INFO - Job 5: Subtask create_table
[2022-11-09 08:17:16,178] {task_command.py:369} INFO - Running <TaskInstance: user_processing.create_table scheduled__2022-11-08T00:00:00+00:00 [running]> on host ce8aab517b0f
[2022-11-09 08:17:23,918] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-08T00:00:00+00:00
[2022-11-09 08:17:24,506] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-11-09 08:17:24,706] {dbapi.py:208} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2022-11-09 08:17:24,739] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2022-11-09 08:17:25,545] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20221108T000000, start_date=20221109T081709, end_date=20221109T081725
[2022-11-09 08:17:27,229] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-09 08:17:31,243] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
